// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAY1J3NacMe2pbFtbpePR9cs9zxnpbO3Y',
    appId: '1:551461799763:web:58f589f840b90597fb03a6',
    messagingSenderId: '551461799763',
    projectId: 'bard-3b721',
    authDomain: 'bard-3b721.firebaseapp.com',
    storageBucket: 'bard-3b721.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeHSBdVtcm239f-YM8tk2vOrAKUTYt6aE',
    appId: '1:551461799763:android:faae5be1bf4db6aafb03a6',
    messagingSenderId: '551461799763',
    projectId: 'bard-3b721',
    storageBucket: 'bard-3b721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyYNvl5H05Jran1qyfWZng_2B7XUIUjCY',
    appId: '1:551461799763:ios:1ec96dfcbbc6f727fb03a6',
    messagingSenderId: '551461799763',
    projectId: 'bard-3b721',
    storageBucket: 'bard-3b721.appspot.com',
    iosBundleId: 'com.example.linqapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyYNvl5H05Jran1qyfWZng_2B7XUIUjCY',
    appId: '1:551461799763:ios:42dda3b9b01ef030fb03a6',
    messagingSenderId: '551461799763',
    projectId: 'bard-3b721',
    storageBucket: 'bard-3b721.appspot.com',
    iosBundleId: 'com.example.linqapp.RunnerTests',
  );
}
